In [12]:
import gdown
import os 
import numpy as np
import pandas as pd

## Load Cleaned dataset

In [13]:
dataset = pd.read_csv('/Users/aya/Documents/Flights_Delay/data/processed/processed_flights.csv')

In [14]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 28 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Unnamed: 0         1000000 non-null  int64
 1   year               1000000 non-null  int64
 2   month              1000000 non-null  int64
 3   day_of_month       1000000 non-null  int64
 4   day_of_week        1000000 non-null  int64
 5   fl_date            1000000 non-null  str
 6   distance           1000000 non-null  float64
 7   origin             1000000 non-null  str
 8   origin_city_name   1000000 non-null  str
 9   origin_state_nm    1000000 non-null  str
 10  dest               1000000 non-null  str
 11  dest_city_name     1000000 non-null  str
 12  dest_state_nm      1000000 non-null  str
 13  op_unique_carrier  1000000 non-null  str
 14  op_carrier_fl_num  1000000 non-null  float64
 15  crs_dep_time       1000000 non-null  int64
 16  crs_arr_time       1000000 non-null  int64
 17  delayed            1000000 non-null  int64
 18  origin_lat         1000000 non-null  float64
 19  origin_lng         1000000 non-null  float64
 20  dest_lat           1000000 non-null  float64
 21  dest_lng           1000000 non-null  float64
 22  distance_zscore    1000000 non-null  float64
 23  distance_outlier   1000000 non-null  bool
 24  season             1000000 non-null  str
 25  is_weekend         1000000 non-null  bool
 26  departure_hour     1000000 non-null  int64
 27  period_of_day      1000000 non-null  str
dtypes: bool(2), float64(7), int64(9), str(10)
memory usage: 200.3 MB

In [15]:
dataset.shape

(1000000, 28)

In [16]:
dataset.head()

,Unnamed: 0,year,month,day_of_month,day_of_week,fl_date,distance,origin,origin_city_name,origin_state_nm,...,origin_lat,origin_lng,dest_lat,dest_lng,distance_zscore,distance_outlier,season,is_weekend,departure_hour,period_of_day
0,0,2024,1,6,6,2024-01-06,475.0,BNA,"Nashville, TN",Tennessee,...,36.124475,-86.678181,42.946932,-87.897064,-0.601835,False,winter,True,12,afternoon
1,1,2024,8,4,7,2024-08-04,2475.0,LAX,"Los Angeles, CA",California,...,33.942496,-118.408049,40.639928,-73.778692,2.746703,False,summer,True,11,morning
2,2,2024,1,12,5,2024-01-12,296.0,SJC,"San Jose, CA",California,...,37.362995,-121.928621,34.200694,-118.358667,-0.901530,False,winter,False,10,morning
3,3,2024,4,3,3,2024-04-03,2248.0,JFK,"New York, NY",New York,...,40.639928,-73.778692,36.080343,-115.152449,2.366644,False,spring,False,6,morning
4,4,2024,11,17,7,2024-11-17,1824.0,CLE,"Cleveland, OH",Ohio,...,41.409407,-81.854691,36.080343,-115.152449,1.656754,False,fall,True,12,afternoon

In [17]:
dataset.tail()

,Unnamed: 0,year,month,day_of_month,day_of_week,fl_date,distance,origin,origin_city_name,origin_state_nm,...,origin_lat,origin_lng,dest_lat,dest_lng,distance_zscore,distance_outlier,season,is_weekend,departure_hour,period_of_day
999995,999995,2024,11,10,7,2024-11-10,517.0,DEN,"Denver, CO",Colorado,...,39.861667,-104.673167,37.036378,-113.510303,-0.531516,False,fall,True,20,evening
999996,999996,2024,5,27,1,2024-05-27,610.0,LGA,"New York, NY",New York,...,40.777242,-73.872606,34.895671,-82.218859,-0.375809,False,spring,False,18,evening
999997,999997,2024,12,12,4,2024-12-12,386.0,SJC,"San Jose, CA",California,...,37.362995,-121.928621,36.080343,-115.152449,-0.750845,False,fall,False,20,evening
999998,999998,2024,5,20,1,2024-05-20,837.0,MSY,"New Orleans, LA",Louisiana,...,29.993272,-90.259028,41.976940,-87.908150,0.004250,False,spring,False,6,morning
999999,999999,2024,7,24,3,2024-07-24,1303.0,SAN,"San Diego, CA",California,...,32.733563,-117.189663,29.984435,-95.341442,0.784459,False,summer,False,13,afternoon

In [26]:
dataset.isna().sum()

Unnamed: 0           0
year                 0
month                0
day_of_month         0
day_of_week          0
fl_date              0
distance             0
origin               0
origin_city_name     0
origin_state_nm      0
dest                 0
dest_city_name       0
dest_state_nm        0
op_unique_carrier    0
op_carrier_fl_num    0
crs_dep_time         0
crs_arr_time         0
delayed              0
origin_lat           0
origin_lng           0
dest_lat             0
dest_lng             0
distance_zscore      0
distance_outlier     0
season               0
is_weekend           0
departure_hour       0
period_of_day        0
dtype: int64

In [21]:
dataset.describe()

,Unnamed: 0,year,month,day_of_month,day_of_week,distance,op_carrier_fl_num,crs_dep_time,crs_arr_time,delayed,origin_lat,origin_lng,dest_lat,dest_lng,distance_zscore,departure_hour
count,1000000.000000,1000000.0,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.000000
mean,499999.500000,2024.0,6.597970,15.786584,3.983077,834.461610,2502.772380,1325.796484,1490.292545,0.208171,36.597999,-94.832342,36.596790,-94.843876,9.939072e-17,12.988599
std,288675.278932,0.0,3.396064,8.787083,2.010310,597.275568,1652.043715,492.424283,518.698428,0.406000,5.987153,18.546931,5.994319,18.559162,1.000000e+00,4.894416
min,0.000000,2024.0,1.000000,1.000000,1.000000,31.000000,1.000000,1.000000,1.000000,0.000000,-14.331662,-176.642482,-14.331662,-176.642482,-1.345211e+00,0.000000
25%,249999.750000,2024.0,4.000000,8.000000,2.000000,399.000000,1150.000000,905.000000,1103.000000,0.000000,32.898639,-111.150260,32.898639,-111.150260,-7.290799e-01,9.000000
50%,499999.500000,2024.0,7.000000,16.000000,4.000000,680.000000,2224.000000,1320.000000,1515.000000,0.000000,36.894604,-87.908150,36.894604,-87.908150,-2.586103e-01,13.000000
75%,749999.250000,2024.0,10.000000,23.000000,6.000000,1069.000000,3717.000000,1735.000000,1925.000000,0.000000,40.777242,-80.951379,40.777242,-80.951379,3.926804e-01,17.000000
max,999999.000000,2024.0,12.000000,31.000000,7.000000,5095.000000,8819.000000,2359.000000,2359.000000,1.000000,71.284861,145.729986,71.284861,145.729986,7.133288e+00,23.000000

In [25]:
dataset.drop(columns=['year' , "month" , "day_of_month" , "day_of_week" ]).describe()

,Unnamed: 0,distance,op_carrier_fl_num,crs_dep_time,crs_arr_time,delayed,origin_lat,origin_lng,dest_lat,dest_lng,distance_zscore,departure_hour
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.000000
mean,499999.500000,834.461610,2502.772380,1325.796484,1490.292545,0.208171,36.597999,-94.832342,36.596790,-94.843876,9.939072e-17,12.988599
std,288675.278932,597.275568,1652.043715,492.424283,518.698428,0.406000,5.987153,18.546931,5.994319,18.559162,1.000000e+00,4.894416
min,0.000000,31.000000,1.000000,1.000000,1.000000,0.000000,-14.331662,-176.642482,-14.331662,-176.642482,-1.345211e+00,0.000000
25%,249999.750000,399.000000,1150.000000,905.000000,1103.000000,0.000000,32.898639,-111.150260,32.898639,-111.150260,-7.290799e-01,9.000000
50%,499999.500000,680.000000,2224.000000,1320.000000,1515.000000,0.000000,36.894604,-87.908150,36.894604,-87.908150,-2.586103e-01,13.000000
75%,749999.250000,1069.000000,3717.000000,1735.000000,1925.000000,0.000000,40.777242,-80.951379,40.777242,-80.951379,3.926804e-01,17.000000
max,999999.000000,5095.000000,8819.000000,2359.000000,2359.000000,1.000000,71.284861,145.729986,71.284861,145.729986,7.133288e+00,23.000000